# Generated by Django 4.0.4 on 2022-05-05 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcg', models.CharField(max_length=100)),
                ('first', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('RAJ2000', models.CharField(max_length=100)),
                ('DEJ2000', models.CharField(max_length=100)),
                ('size_arcmin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('u_size', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=100)),
                ('grp', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('com', models.CharField(max_length=200)),
                ('tno', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.catalogue')),
                ('labelled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
