# Generated by Django 4.0.4 on 2022-05-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
